# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-08-24 08:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_cacheme', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invalidation',
            name='tags',
            field=models.CharField(default='', max_length=5000),
        ),
    ]
